# Generated by Django 5.0.6 on 2024-05-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre', 'camada'), 'verbose_name': 'Course', 'verbose_name_plural': 'The courses'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
    ]
