# Generated by Django 5.0.6 on 2024-06-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_curso_options_profesor_cursos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Competencia',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Nadador',
        ),
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ('nombre', 'camada'), 'verbose_name': 'Competence', 'verbose_name_plural': 'Competences'},
        ),
    ]
