# Generated by Django 5.0.6 on 2024-06-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_curso_competencia_rename_estudiante_nadador_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Entrenador',
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='cursos',
            new_name='competencias',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
