# Generated by Django 5.0.6 on 2024-06-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_profesor_entrenador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='profesion',
            new_name='club',
        ),
    ]
