# Generated by Django 5.0.6 on 2024-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_profesion_entrenador_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='competencias',
        ),
        migrations.AddField(
            model_name='nadador',
            name='competencias',
            field=models.ManyToManyField(to='AppCoder.competencia'),
        ),
    ]
