# Generated by Django 5.0.6 on 2024-06-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_competencia_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='nombre',
            new_name='estilo',
        ),
    ]
