# Generated by Django 5.0.6 on 2024-06-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_rename_nombre_competencia_estilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='camada',
            new_name='distancia',
        ),
    ]
