# Generated by Django 5.0.6 on 2024-06-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_rename_camada_competencia_distancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='estilo',
            new_name='evento',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='distancia',
        ),
        migrations.AddField(
            model_name='competencia',
            name='record',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
