# Generated by Django 5.0.6 on 2024-06-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_rename_estilo_competencia_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nadador',
            name='competencias',
        ),
    ]
